name: 'tests'

on:
    pull_request:
    push:
        branches: [ master ]

permissions:
    contents: read

jobs:
    phpunit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.0', '8.1', '8.2', '8.3', '8.4' ]
        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - run: composer install --no-interaction --no-progress

            - run: vendor/bin/phpunit
