name: 'trigger gprotect deploy'

on:
    release:
        types: [ published ]
    workflow_dispatch:
        inputs:
            RELEASE_TAG:
                description: 'The version to deploy to github pages.'
                required: false
                type: string

permissions:
    contents: read

jobs:
    trigger_workflow:
        runs-on: ubuntu-latest
        steps:
            - name: get release tag from event name
              if: github.event_name == 'release'
              run: echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

            - name: get release tag from input variable
              if: github.event_name == 'workflow_dispatch'
              run: echo "RELEASE_TAG=${{ inputs.RELEASE_TAG }}" >> $GITHUB_ENV

            - name: trigger gprotect workflow
              if: env.RELEASE_TAG != ''
              run: |
                  RELEASE_TAG="${{ env.RELEASE_TAG }}"
                  curl -sL \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.TRIGGER_GPROTECT_WORKFLOWS }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/gambio/gprotect/actions/workflows/deploy_pages.yml/dispatches \
                    -d '{"ref":"master","inputs":{"RELEASE_TAG":"${{ env.RELEASE_TAG }}"}}'
